#!/usr/bin/env bash
# Script that displays username, user ID, and home directory from /etc/passwd

  while IFS=':' read -r username _ uid _ _ home _
do
	echo "$username:$uid:$home"
done < /etc/passwd
