#!/usr/bin/env bash
# This script displays visitor IP and HTTP status code from Apache log file
# Format: IP HTTP_CODE
# Uses awk to parse the apache-access.log file

awk '{print $1, $9}' apache-access.log
