#!/usr/bin/env bash
# Script that groups visitors by IP and HTTP status code from Apache log file

awk '{print $1, $9}' /var/log/apache2/access.log | sort | uniq -c | sort -nr | awk '{printf "%7d %s %s\n", $1, $2, $3}'
