#!/usr/bin/env bash
# Script that groups visitors by IP and HTTP status code from Apache log file

# Read the Apache log file and extract IP and status code, then sort and count
grep -E "^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+" /var/log/apache2/access.log | \
sed 's/^\([0-9.]*\).*" \([0-9]*\) .*/\1 \2/' | \
sort | \
uniq -c | \
sort -nr | \
sed 's/^ *\([0-9]*\) \(.*\)/\1 \2/'
