#!/usr/bin/env bash
# This script loops from 1 to 10 and displays "bad luck" for the 4th iteration, "good luck" for the 8th iteration, and "Best School" for other iterations

i=1
while [ $i -le 10 ]
do
	if [ $i -eq 4 ]
	then
	    echo "bad Luck"
	elif [ $i -eq 8 ]
	then
	    echo "good Luck"
	else
	    echo "Best school"
   fi
	((i++))
done
