#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely and handles SIGTERM signal

invincible() {
	echo "I am invincible!!!"
}

trap invincible SIGTERM

while true
do
	echo "To infinity and beyond"
	sleep 2
done
